REG/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Course/',include('Register.urls')),
    path('Users/',include('Users.urls')),
    path('',include('home.urls')),
]

Register/urls.py
from django.urls import path

from . import views

app_name ="Register"

urlpatterns = [
    path('',views.index,name='index'),
    path('<course_code>',views.ShowCourse,name='ShowCourse'),
    path("<course_code>/apply", views.apply, name="apply"),
    path("<course_code>/remove", views.removeCourse, name="remove"),
]

Users/urls.py
from django.urls import path


from . import views

app_name = "Users"

urlpatterns = [
    path("",views.index,name="studentinfo"),
    path("login",views.login_view,name="login"),
    path('logout',views.logout_view,name="logout"),
]

home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path("",views.index,name="index"),
]

Register/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Course(models.Model):
    course_code = models.CharField(max_length=5 , primary_key= True)
    course_name = models.CharField(max_length=64)
    semester = models.PositiveIntegerField()
    academic_year = models.PositiveIntegerField()
    limit_seat = models.PositiveIntegerField()
    siting = models.PositiveIntegerField()
    status = models.BooleanField()
    student = models.ManyToManyField(User, blank=True,related_name="enroll")
    
    def __str__(self):
        return f"{self.course_code} {self.course_name}  "

Users/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

Register/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from .models import Course
from django.db.models import Count

# Create your views here.


def index(request):
    
    return render(request,"registers/index.html",{
        "Course": Course.objects.all(),
        
    })


def ShowCourse(request, course_code):
    info = get_object_or_404(Course,pk=course_code)
    students = info.student.all()

    return render(request,"registers/course_info.html",{
        "Course": info,
        "student":info.student.all(),
        "seat":students.count()
    })


def apply(request, course_code):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("Users:login"))

    x = get_object_or_404(Course,pk=course_code)
    if request.user not in x.student.all():
        x.student.add(request.user)
        x.siting += 1 
    return HttpResponseRedirect(reverse("Register:ShowCourse",args=(course_code,)))


def removeCourse(request , course_code):

    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("Users:login"))

    x = get_object_or_404(Course,pk=course_code)
    if request.user in x.student.all():
        x.student.remove(request.user)
        x.siting -=  1
    return HttpResponseRedirect(reverse("Register:ShowCourse",args=(course_code,)))
    
   

Users/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from Register.models import Course
from django.shortcuts import get_object_or_404

# Create your views here.


def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("Users:login"))
    get_subject = request.user.enroll.all()
    return render(request, "users/studentinfo.html",{
        "subject":get_subject,
    })
        
    
def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username,password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("Users:studentinfo"))
        else:
            return render(request, "users/login.html",{
                "message": "Invalid Username or Password."
            })
    return render(request, "users/login.html")

def logout_view(request):
    logout(request)

    return HttpResponseRedirect(reverse("Users:login"))
    

home/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request,"home/index.html",{
    })

Register/templates/registers/course_info.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Register</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    
        <style>
            body,html{
            background-image: url("/static/images/bg-pb.jpg");
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: 100% 100%;
            }
            dl,ul{
                color:darkblue;
                font-size: medium;
                margin-left:10px;
                
            }
            h2{
                background-color: rgb(236, 184, 234);
                margin-left:5px;
            }

            div.foo {
                position: absolute;
                top: 85%;
                left: 1%;
            }
            div.a{
                left: 1%;
                margin-left: 15px;
            }

        </style>
    
    </head>
    <body>
        <h2> &#128214 Course: {{ Course.course_code }}</h2>
        <br>
        <dl>
            <dd>Course Name: {{ Course.course_name }}</dd>
            <dd>Open:{{Course.status}}</dd>
            <dd>status: {{seat}}/{{Course.limit_seat}} seats</dd>
        </dl>
        
        {% if request.user.is_superuser %}
        <br>
        <h2>&#128587 Students</h2>
        <ul>
            {% for y in student %}
            <li>{{ y.first_name }} {{y.last_name}}</li>
            {% empty %}
            <li>No Student</li>
            {% endfor %}
        </ul>
        
        {% else %}
        
            <br>
            <div class="a">
                {% if request.user not in student %}
                    {% if Course.status and seat < Course.limit_seat %}
                    
                        <p><a href="{% url 'Register:apply' Course.course_code %}"  class="btn btn-success">Apply course &#128221</a></h3>
                    {% else %}
                        {% if Course.status == False %}
                            <p><h4 style="color:crimson;">Closed &#9203</a></h4>
                        {% else %}
                            <p><h4 style="color:crimson;">seat full &#128560</a></h4>
                        {% endif %}        
                    {% endif %}
                {% else %}
                
                    <h4 style="color: rgba(64, 139, 41, 0.979);">Already Register</h4>
                    <p><a href="{% url 'Register:remove' Course.course_code %}" class="btn btn-danger">&#9888 Remove course &#9888</a></h3>
                
                {% endif %}
            {% endif %}
            </div>
        <div style="bottom: auto;" class="foo" >
            <div class="btn-group-vertical">
                <a href= "{% url 'Register:index'%}" class="btn btn-warning"> select course </a>
                <a href= "{% url 'Users:studentinfo'%}" class="btn btn-secondary"> return to profile </a> 
            </div>
        </div>
    </body>
<html>

Register/templates/registers/index.html
<!DOCTYPE html>
<html>

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">
    <link rel="stylesheet" href="css/style.css">

    <style>

        #parent { white-space: nowrap; }
        .child { display: inline-block; }   
        h1{
            color: rgb(218, 40, 218);
            
        }
        p{
            color: rgb(179, 65, 214);
        }
        b{
            color: rgb(4, 1, 10);
            margin-top: 1%;
            margin-left: 2%;
            font-size: 200%;
            
        }
        
        body,html{
            background-image: url("/static/images/bg-pb.jpg");
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: 100% 100%;
        }
        
        br{
            background-color: rgb(199, 231, 82);
        }

    </style>


</head>



<body>
    <div class="alert alert-warning" role="alert">
        &#128227 Enrollment Now 19 Sep - 28 Sep 2077 !
    </div>

    <p style="text-align: center;"><b> &#10084 &#128153 &#128154 Course List &#128155 &#129505 &#128156</b></p>
    <br>   
    <ul style="text-align: center;">
    {% for x in Course  %}
        <a href="{% url 'Register:ShowCourse' x.course_code %}" class="btn btn-light">{{ x }} </a>
            
        {% if x.status == True %}
            <p style="text-shadow: 1px 2px 2px #FFCC00;;">Status :&#9989</p>
            {% else %}
            <p style="text-shadow: 1px 2px 2px #FFCC00;">Status : &#9940</p>
        {% endif %}
        {% endfor %}
    </ul>

    

</body>
    
    <a href="{% url 'Users:studentinfo' %}" class="btn btn-dark" style="margin-left: 1%;margin-bottom: 5px;" ><h5>&#9194 Return </h5></a>


</html>

Register/templates/registers/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>Course</title>
        <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    </head>

    
    <body>
        {% block body %}
        {% endblock body %}
    </body>
</html>

Users/templates/users/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>Users</title>
        
    </head>
    <body>
        {% block body %}
        {% endblock body %}
    </body>
</html>

Users/templates/users/login.html
<!DOCTYPE html>

<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #5e0779 !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #0aeb82;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
							<br>
							<p style="text-align:center;margin-top: auto;"> <a href="{% url 'home:index' %}" class="btn btn-primary">home</a></p>

							{% if message %}
							{{ message }}
							{% endif %}

						</form>
					
				</div>
                
										
                
				</div>
			</div>
		</div>
	</div>
</body>

</html>

Users/templates/users/studentInfo.html
<!DOCTYPE html> 
{% load static %}
<html>
   
    <head>
        <title>Users</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
        
        <style>
            body,html{
                background-image: url("/static/images/joker.jpg");
                background-repeat: no-repeat;
                background-attachment: fixed;
                background-size: 100% 100%;
            }
            ul{
                color: rgb(131, 207, 101);
                margin: 10px;
                margin-top: 2px;
            }
            div.foo {
                position: absolute;
                top: 85%;
                left: 1%;
            }
        </style>
    </head>
    
    <body>
        <h1 style="color: blueviolet;margin: 20px;"> Welcome, {{ request.user.username }} &#128075 </h1>

        <ul>
            <li>Name: {{ request.user.first_name }} {{request.user.last_name}}</li>
            <li>Email: {{request.user.email}} </li>
            <br>
            
           
        </ul>

        {% if request.user.is_superuser %}
        {% else %}

            <h3 style="color:blueviolet;margin: 20px;">&#128218 Registered Subjects</h3>
            <ul>
                {% for x in subject  %}
                    <li>{{ x }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <div class="foo">
            <p><a href="{% url 'Register:index' %}" class="btn btn-outline-warning">Enrollment &#128221</a></p>
            <p><a href="{% url 'Users:logout' %}" class="btn btn-outline-danger">Log out</a></p>
        </div>
        
    </body>
</html>

home/templates/home/index.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>index</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    
        <style>
            body,html{
                background-image: url('static/images/tu.jpg');
                background-repeat: no-repeat;
                background-attachment: fixed;
                background-size: 100% 100%;
            }
            figure.motto{
                background-color: rgb(240, 230, 147);
                position: absolute;
                bottom: 0px;
                right: 10px;
                width: 400px;
                height: 100px;
                text-align: left;
            }
            div.tu{
                bottom: 4%;
                left: 10px;
                width: 400px;
                height: 100px;
                position: absolute;
            }
        </style>
    
    
    </head>
    
    <body>
        <h1 style="text-align: center;background-color:crimson;">&#128081 Register TU &#128081</h1>
        <div class="alert alert-warning" role="alert">
           &#128227 Enrollment Now 19 Sep - 28 Sep 2077 !
        </div>

        <div class="tu">
        <img src="{%static 'images/tulong.png'%}" alt="...">
        </div>
        
        <p style="text-align: center;"><a href="{% url 'Users:login' %}" class="btn btn-success">Log in</a></p>

        
        <figure class="motto">
            <blockquote class="blockquote">
              <p> The greatest lesson I have learn in school is that I have learn nothing. </p>
            </blockquote>
            <figcaption class="blockquote-footer">
              Some TU student <cite title="Source Title"></cite>
            </figcaption>
          </figure>
    </body>


    
</html>

home/templates/home/layout.html
{% load static %}
<!DOCTYPE html>
<html>

    <head>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js%22%3E"></script>
        



        <style>

            body,html{
            background-color: aqua;
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: 100% 100%;
            }


        </style>

    </head>


    <body>

        <h1>Course List</h1>

        <ul>
        {% for x in Course  %}
            <li><a href="{% url 'Register:ShowCourse' x.course_code %}">{{ x }} </a></li>
        {% endfor %}
        </ul>

        <p>{{Course.siting}}</p>

        <a href="{% url 'Users:studentinfo' %}">Return</a>

    </body>

</html>